//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        public int kullanici_id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string sektor { get; set; }
    }
}
